### ISSUE TITLE
Can't import plugin into Touch Portal

### ISSUE THREAD

**Issue by d-fect** [KillerBOSS2019/Foobar2000-Plugin-for-TP#1]
I installed the foobar plugin, and that works correctly. I can control foobar from the webpage.

I then downloaded the Foobar2000.tpp from releases, filesize 6903KB, but when I try to import it into Touch Portal I get the error message "Failed to load plug-in."

Also having problems importing the premade page. It says it's imported OK, but nothing pops up. I think that might be because I haven't been able to import the plugin.

Using Touch Portal 2.3.007 and Win10. 

This is exactly the plugin I've been looking for, so I hope the problem can be fixed.

**Comment by DamienStaebler** [comment]
I am sorry about that it's package problem but it should still work if you just import it from the main screen Not from the settings

**Comment by DamienStaebler** [comment]
As for the page I am not sure why isn't working but I'll reupload it

**Comment by d-fect** [comment]
Importing plugin from main screen worked. Strange... But thanks!

I'll check out the new page upload when I have the time.

**Comment by DamienStaebler** [comment]
Ye it's my fault it's because the package problem.but it should still work with no issues
