### ISSUE TITLE
Foobar Portable 1.6.7

### ISSUE THREAD

**Issue by JCKeanu** [KillerBOSS2019/Foobar2000-Plugin-for-TP#2]
Hi, I use Foobar Portable 1.6.7
If I try to install the Plugin it stops by "importing Foobar2000/Main"
is there a workaround
THX Frank

**Comment by DamienStaebler** [comment]
You will need to install [Beefweb](https://foobar2000.org/components/view/foo_beefweb) plugin for Foobar and then you can import the plugin to TP

**Comment by JCKeanu** [comment]
THX,
Beefweb was already installed, i remove the security settings user and PW  Port 8880
same result. Process hold on during install / no error
The Page import of the foobar.tpz file fails too with an unknown Error.
3.0.6.00 and Java JDK 17

**Comment by DamienStaebler** [comment]
You downloaded this right? [Foobar2k](https://github.com/KillerBOSS2019/Foobar2000-Plugin-for-TP/releases/download/1.0.0/Foobar2000.tpp)

**Comment by DamienStaebler** [comment]
Also about that page error you may want to ask this issue in TouchPortal Discord to get help with that
