### ISSUE TITLE
a few more questions

### ISSUE THREAD

**Issue by tkymuk** [KillerBOSS2019/Foobar2000-Plugin-for-TP#4]
How do you install this plugin? Your installation instructions are not clear at all. What do I do with the .tpz file? The best I can gather is that its a godot game engine file. How does this install into Touch Portal?

**Comment by DamienStaebler** [comment]
This is where the .tpz is located

**Comment by DamienStaebler** [comment]
https://github.com/KillerBOSS2019/Foobar2000-Plugin-for-TP/blob/main/Foobar_Control.tpz
